C FORTRAN 77 PROGRAM CONVERT BETWEEN RECTANGULAR COORDINATES AND POLAR
C COORDINATES

C VERSION 2
C UPDATE USED COMPUTED GOTO 
C CHANGED CHARACTER CIN TO INTEGER IN
C USE X*X  INSTEAD OF X**2 (SAME FOR Y)

C VERSION 3
C ADD D0 TO ALL NUMBERS TO FIX BUG
C FORMAT ANSWERS
C ADDED COMMENTS ON HOW TO CALCULATE ON A TI-83 (DEBUGGING PURPOSES)
C REPLACE DATAN(Y/X) WITH DATAN2(Y,X) 

C DEBUGGING (USING A TI-83) 

C POLAR TO RECTANGULAR
C 2ND ANGLE
C P->RX(R,THETA) CALCULATE X
C P->RY(R,THETA) CALCULATE Y

C RECTANGULAR TO POLAR
C 2ND ANGLE
C R->PR(X,Y) CALCULATE RADIUS(R)
C R->PTHETA(X,Y) CALCULATE ANGLE (THETA)
C IN TI83 THETA IS LITERALLY THE THETA LETTER WHICH IS NOT IN F77
  
      PROGRAM COORD
      IMPLICIT NONE
      INTEGER IN
      DOUBLEPRECISION X,Y,A,R,PI
      PARAMETER(PI=3.141592654D0)
C A IS ANGLE

10    WRITE(*,*) '1 RECTANGULAR TO POLAR'
      WRITE(*,*) '2 POLAR TO RECTANGULAR'
      READ(*,*) IN

C COMPUTED GOTO
C IF IN .EQ. 1 GOTO 20
C IF IN .EQ. 2 GOTO 30
C ELSE GOTO 10
      GOTO(20,30) IN
      GOTO 10
20    CONTINUE
      WRITE(*,*) 'X,Y'
      READ(*,*) X,Y
      R=DSQRT((X*X)+(Y*Y))
      A=DATAN2(Y,X)

C CONVERT A FROM RADIANS TO DEGREES
      A=A*(1.8D2/PI)

      WRITE(*,'(A2,F17.9,X,A2,F17.9,X,A4)') 'R=',R,'A=',A,'DEGS'
      GOTO 999
30    CONTINUE
      WRITE(*,*) 'R,A (DEGS)'
      READ(*,*) R,A

C CONVERT A FROM DEGREES TO RADIANS
      A=A*(PI/1.8D2)

      X=R*DCOS(A)
      Y=R*DSIN(A)
      WRITE(*,'(A2,F17.9,X,A2,F17.9)') 'X=',X,'Y=',Y

999   STOP
      END
