C PROGRAM TO CALCULATE HOW MANY FLOPPIES ARE NEEDED
C ASSUMES 3.5IN 1440K FLOPPIES
      PROGRAM FLOPPY
      IMPLICIT NONE
      DOUBLEPRECISION FY,COUNT
      PARAMETER(FY=1440.0) 
C SIZE OF FLOPPY 1440K
      CHARACTER UNIT

      WRITE(*,*) 'PROGRAM ASSUMES 3.5IN 1440K FLOPPIES'
      WRITE(*,*)
      WRITE(*,*) 'UNIT,COUNT'
      READ(*,*) UNIT, COUNT

      IF(UNIT .EQ. 'B') THEN
        WRITE(*,900) ((1.0/1024.0)*COUNT)/FY
      ELSEIF(UNIT .EQ. 'K') THEN
        WRITE(*,900) COUNT/FY
      ELSEIF(UNIT .EQ. 'M') THEN
        WRITE(*,900) (1024.0*COUNT)/FY
      ELSEIF(UNIT .EQ. 'G') THEN
        WRITE(*,900) ((1024.0**2)*COUNT)/FY
      ELSE
        WRITE(*,*) 'INVALID UNIT'
        GOTO 999
      ENDIF
      WRITE(*,*) '(ROUND ALL DECIMALS UP TO NEXT WHOLE NUMBER)'


900   FORMAT(F8.2, ' FLOPPIES')
999   STOP
      END
