C FORTRAN 77 PROGRAM TO CONVERT DEGREES TO RADIANS OR 
C RADIANS TO DEGREES
C VERSION 2
C BUG FIX ADD D0 TO ALL NUMBERS TO GET DOUBLEPRECISION
C INCREASED FORMAT TO F17.9

      PROGRAM RAD
      IMPLICIT NONE
      CHARACTER CIN
      DOUBLEPRECISION X,PI
      PARAMETER(PI=3.141592654D0)

10    WRITE(*,*) '''R'',X RADIANS TO DEGREES'
      WRITE(*,*) '''D'',X DEGREES TO RADIANS'
      READ(*,*) CIN,X

      IF(CIN .EQ. 'R') THEN
        X=X*(1.8D2/PI) 
        WRITE(*,900) 'X=',X,'DEGS'
      ELSEIF(CIN .EQ. 'D') THEN
        WRITE(*,*) 'D'
        X=X*(PI/1.8D2)
        WRITE(*,900) 'X=',X,'RADS'
      ELSE 
        WRITE(*,*) 'INVALID'
        GOTO 10
      ENDIF

900   FORMAT(A2,X,F17.9,X,A4)
      STOP
      END
